server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: ${NOTIFY_SMTP_HOST:localhost}
    port: ${NOTIFY_SMTP_PORT:2525}
    username: ${NOTIFY_SMTP_USERNAME:}
    password: ${NOTIFY_SMTP_PASSWORD:}
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

gemini:
  api:
    key: ${GEMINI_API_KEY:AIzaSyBCLV_pwlvg-KhoCRRQjl6U8ejO63FdEPQ}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    model: gemini-2.0-flash
    enabled: ${GEMINI_ENABLED:true}

ai:
  service-url: ${gemini.api.url}
  api-key: ${gemini.api.key}
  enabled: ${gemini.api.enabled}

logging:
  level:
    '[org.springframework]': INFO
    '[com.example.meeting]': DEBUG

security:
  user:
    name: admin
    password: admin_password
    roles: ADMIN, USER

notifications:
  enabled: true
  default-offsets-minutes: [30, 60, 1440] # 30 minutes, 1 hour, 1 day
  method: [EMAIL, IN_APP]
  facilities-emails: ["facilities@company.local", "it-support@company.local"]
  smtp:
    host: localhost
    port: 2525
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000